[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/api/debates/*"
  to = "/.netlify/functions/debates/:splat"
  status = 200

[[redirects]]
  from = "/api/trainer"
  to = "/.netlify/functions/trainer"
  status = 200
