import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,normalize} from 'node:path';
import {createHash} from 'node:crypto';
const root=resolve('.'),port=Number(process.env.PORT||4173),feedUrls=(process.env.NEWS_RSS_URL||'https://feeds.nos.nl/nosnieuwsalgemeen').split(',').map(url=>url.trim()).filter(Boolean),openAiKey=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL||'gpt-5';
const cache={articles:[],updatedAt:null,analyses:new Map()},rateLimits=new Map(),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};
const decode=value=>String(value||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"');
const plain=value=>decode(value).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const tag=(xml,name)=>{const match=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return match?plain(match[1]):''};
const image=xml=>{const media=xml.match(/<media:content[^>]+url=["']([^"']+)/i)||xml.match(/<enclosure[^>]+url=["']([^"']+)/i);return media?decode(media[1]):''};
function categoryFor(text){const value=text.toLowerCase();if(/klimaat|stikstof|energie|uitstoot/.test(value))return 'Klimaat';if(/\bai\b|tech|digitaal|internet|cyber/.test(value))return 'Technologie';if(/europa|\beu\b|brussel/.test(value))return 'Europa';if(/school|onderwijs|student/.test(value))return 'Onderwijs';if(/economie|inflatie|bedrijf|begroting|bank/.test(value))return 'Economie';if(/kabinet|kamer|minister|verkiez/.test(value))return 'Nederlandse politiek';if(/wetenschap|onderzoek|universiteit/.test(value))return 'Wetenschap';if(/rusland|oekraïne|amerika|china|israël|gaza|buitenland/.test(value))return 'Internationale politiek';return 'Maatschappij'}
function slugify(text,id){const slug=text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,72);return `${slug||'onderwerp'}-${id.slice(0,6)}`}
function parseRss(xml,sourceUrl){const source=tag(xml,'title')||new URL(sourceUrl).hostname;return [...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(match=>{const item=match[1],sourceUrl=tag(item,'link'),title=tag(item,'title'),publishedAt=Date.parse(tag(item,'pubDate'))||Date.now(),id=createHash('sha256').update(sourceUrl||title).digest('hex').slice(0,16),summary=tag(item,'description').slice(0,360);return {id,slug:slugify(title,id),title,summary,category:categoryFor(`${title} ${summary}`),source,sourceUrl,imageUrl:image(item),imageAlt:title,publishedAt:new Date(publishedAt).toISOString(),importance:0,debateWorthiness:0,tags:[],isLive:true};}).filter(article=>article.title&&article.sourceUrl)}
async function refreshNews(){const results=await Promise.allSettled(feedUrls.map(async url=>{const response=await fetch(url,{headers:{'User-Agent':'DEBATTAFEL/1.0'},signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Nieuwsfeed niet beschikbaar');return parseRss(await response.text(),url)}));const articles=results.flatMap(result=>result.status==='fulfilled'?result.value:[]),unique=[...new Map(articles.map(article=>[article.sourceUrl,article])).values()].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,5);if(!unique.length)throw Error('Geen bruikbare artikelen uit de ingestelde nieuwsfeed.');cache.articles=unique;cache.updatedAt=new Date().toISOString();return unique}
async function latestNews(){if(cache.articles.length&&Date.now()-Date.parse(cache.updatedAt)<900000)return {articles:cache.articles,updatedAt:cache.updatedAt,stale:false};try{return {articles:await refreshNews(),updatedAt:cache.updatedAt,stale:false}}catch(error){if(cache.articles.length)return {articles:cache.articles,updatedAt:cache.updatedAt,stale:true,warning:'Nieuwsbron tijdelijk niet bereikbaar; laatste succesvolle update wordt getoond.'};throw error}}
function permitted(request){const ip=request.socket.remoteAddress||'unknown',now=Date.now(),events=(rateLimits.get(ip)||[]).filter(time=>now-time<60000);if(events.length>=10)return false;events.push(now);rateLimits.set(ip,events);return true}
async function openAiJson(instructions,input){if(!openAiKey){const error=Error('AI-analyse is nog niet geconfigureerd.');error.status=503;throw error}const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${openAiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,input,instructions,text:{format:{type:'json_object'}},max_output_tokens:1200,store:false}),signal:AbortSignal.timeout(30000)});if(!response.ok){const error=Error('AI-analyse is tijdelijk niet beschikbaar.');error.status=502;throw error}const result=await response.json();try{return JSON.parse(result.output_text)}catch{const error=Error('AI-analyse gaf geen bruikbaar antwoord.');error.status=502;throw error}}
const strings=(value,max)=>Array.isArray(value)?value.filter(item=>typeof item==='string').map(item=>item.slice(0,500)).slice(0,max):[];
async function debateFor(article){if(cache.analyses.has(article.id))return cache.analyses.get(article.id);const raw=await openAiJson('Je bent een neutrale debatredacteur. Analyseer uitsluitend het meegeleverde artikel. Verzin geen feiten, bronnen, cijfers of citaten. Label onzekerheid. Lever uitsluitend geldig JSON met statement, context, facts (max 5), pro (exact 3), con (exact 3), counterArguments (max 3), weakPoints (max 3), questions (exact 3).',`Artikelbron: ${article.source}\nTitel: ${article.title}\nSamenvatting uit RSS: ${article.summary}`),analysis={statement:String(raw.statement||'').slice(0,500),context:String(raw.context||'').slice(0,1200),facts:strings(raw.facts,5),pro:strings(raw.pro,3),con:strings(raw.con,3),counterArguments:strings(raw.counterArguments,3),weakPoints:strings(raw.weakPoints,3),questions:strings(raw.questions,3),generatedAt:new Date().toISOString(),label:'AI-analyse — controleer altijd de oorspronkelijke bron'};cache.analyses.set(article.id,analysis);return analysis}
async function getBody(request){let result='';for await(const chunk of request){result+=chunk;if(result.length>20000)throw Error('Verzoek is te groot.')}try{return JSON.parse(result||'{}')}catch{const error=Error('Ongeldige JSON.');error.status=400;throw error}}
async function trainer(input){const statement=plain(input.statement).slice(0,500),argument=plain(input.argument).slice(0,1500),round=Number(input.round)||1;if(statement.length<10||argument.length<10){const error=Error('Vul een stelling en argument van minimaal 10 tekens in.');error.status=400;throw error}const raw=await openAiJson('Je bent een neutrale debatcoach. Beoordeel geen persoon, alleen het argument. Verzin geen feiten. Lever uitsluitend geldig JSON met feedback, argumentType, weakPoint, counterArgument, followUpQuestion en nextExercise. Houd ieder veld kort in het Nederlands.',`Stelling: ${statement}\nArgument van gebruiker: ${argument}\nRonde: ${round}`);return {round,feedback:Object.fromEntries(['feedback','argumentType','weakPoint','counterArgument','followUpQuestion','nextExercise'].map(key=>[key,String(raw[key]||'').slice(0,800)]))}}
function send(response,status,payload){response.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});response.end(JSON.stringify(payload))}
async function api(request,response,url){if(!permitted(request))return send(response,429,{error:'Te veel verzoeken. Probeer het over een minuut opnieuw.'});if(request.method==='GET'&&url.pathname==='/api/news'){try{return send(response,200,await latestNews())}catch{return send(response,503,{error:'Nieuws kon tijdelijk niet worden geladen. Probeer het later opnieuw.'})}}if(request.method==='GET'&&url.pathname.startsWith('/api/debates/')){try{const {articles}=await latestNews(),article=articles.find(item=>item.slug===decodeURIComponent(url.pathname.slice(13)));if(!article)return send(response,404,{error:'Dit artikel is niet beschikbaar.'});return send(response,200,{article,analysis:await debateFor(article)})}catch(error){return send(response,error.status||503,{error:error.message||'Debatanalyse kon niet worden geladen.'})}}if(request.method==='POST'&&url.pathname==='/api/trainer'){try{return send(response,200,await trainer(await getBody(request)))}catch(error){return send(response,error.status||503,{error:error.message||'De trainer is tijdelijk niet beschikbaar.'})}}return send(response,404,{error:'API-route niet gevonden.'})}
createServer(async(request,response)=>{try{const url=new URL(request.url,`http://${request.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/'))return api(request,response,url);const requested=normalize(decodeURIComponent(url.pathname)).replace(/^([/\\])+/,''),candidate=resolve(root,requested||'index.html');if(!candidate.startsWith(root))throw Error('forbidden');let file=candidate;try{if((await stat(file)).isDirectory())file=resolve(root,'index.html')}catch{file=resolve(root,'index.html')}const content=await readFile(file);response.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});response.end(content)}catch{response.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});response.end('Niet gevonden')}}).listen(port,'0.0.0.0',()=>console.log(`DEBATTAFEL draait op http://localhost:${port}`));
