import {getLatestNews,getNewsByCategory,getLastSuccessfulUpdate,getDebate,trainerRound,categories} from './services/news-service.js';
import {favorites} from './services/favorites.js';
import {card,toolbar,empty,bindFavorites,escapeHtml} from './components.js';
const main=document.querySelector('main'),appTitle='DEBATTAFEL',menu=document.querySelector('nav'),menuButton=document.querySelector('.menu-toggle');
menuButton.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});
const updateFavoriteCount=()=>document.querySelector('#favorite-count').textContent=`(${favorites().length})`;
const formatTime=meta=>new Intl.DateTimeFormat('nl-NL',{dateStyle:'long',timeStyle:'short'}).format(new Date(meta?.updatedAt||Date.now()));
function shell(title,subtitle,body){document.title=`${title} — ${appTitle}`;main.innerHTML=`<section class="hero"><span class="eyebrow">Onafhankelijke debatredactie</span><h1>${escapeHtml(title)}</h1><p>${escapeHtml(subtitle)}</p></section><div class="content">${body}</div>`;main.focus();}
function renderResults(items,query='',category=''){const sort=document.querySelector('#sort')?.value||'newest',needle=query.trim().toLocaleLowerCase('nl');const results=items.filter(item=>(!category||item.category===category)&&(!needle||[item.title,item.summary,item.category,item.source,...(item.tags||[])].join(' ').toLocaleLowerCase('nl').includes(needle))).sort((a,b)=>sort==='importance'?b.importance-a.importance:sort==='debate'?b.debateWorthiness-a.debateWorthiness:new Date(b.publishedAt)-new Date(a.publishedAt));document.querySelector('#results').innerHTML=results.length?results.map(card).join(''):empty('Geen resultaten gevonden.','Probeer een andere zoekterm of filter.');bindFavorites(items);}
function bindControls(items){bindFavorites(items);for(const element of ['search','category','sort'])document.querySelector(`#${element}`)?.addEventListener(element==='search'?'input':'change',()=>renderResults(items,document.querySelector('#search').value,document.querySelector('#category').value));}
async function newsPage(category=''){try{const feed=await getLatestNews(),articles=category?feed.articles.filter(article=>article.category===category):feed.articles,heading=category||'De vijf van vandaag';shell(heading,category?'Actuele artikelen binnen deze categorie.':'Vandaag op tafel.',`<p class="update">Geüpdatet op ${formatTime({updatedAt:feed.updatedAt})}${feed.stale?' · Laatste succesvolle update':''}</p>${feed.warning?`<p class="notice">${escapeHtml(feed.warning)}</p>`:''}${toolbar()}<div id="results">${articles.length?articles.map(card).join(''):empty('Geen onderwerpen in deze categorie.','Probeer later opnieuw.')}</div>`);bindControls(articles);}catch(error){shell('De vijf van vandaag','Vandaag op tafel.',empty('Nieuws tijdelijk niet beschikbaar.',error.message||'Probeer het later opnieuw.'));}}
const list=items=>`<ul>${items.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`;
async function debate(slug){try{const {article,analysis}=await getDebate(slug);shell(article.title,'Debatweergave op basis van het oorspronkelijke artikel.',`<article class="debate"><header class="debate-header"><span class="badge">AI-analyse</span><p class="statement">${escapeHtml(analysis.statement)}</p><p class="notice">${escapeHtml(analysis.label)}</p><div class="debate-actions"><button class="button secondary favorite" data-id="${escapeHtml(article.id)}">Bewaar debat</button><button id="share" class="button secondary">Deel</button></div></header><section class="debate-section"><span class="badge">FACT · Broncontext</span><h2>Wat is er aan de hand?</h2><p>${escapeHtml(analysis.context||article.summary)}</p><p><a href="${escapeHtml(article.sourceUrl)}" target="_blank" rel="noopener">Lees het oorspronkelijke artikel bij ${escapeHtml(article.source)} ↗</a></p>${list(analysis.facts)}</section><section class="debate-section columns"><div class="pro"><span class="badge">ARGUMENT · Pro</span><h3>De sterkste voorstanders</h3>${list(analysis.pro)}</div><div class="con"><span class="badge">ARGUMENT · Con</span><h3>De sterkste tegenwerpingen</h3>${list(analysis.con)}</div></section><section class="debate-section"><span class="badge">ARGUMENT · Tegenargumenten</span><h2>Waar beide kanten rekening mee moeten houden</h2>${list(analysis.counterArguments)}</section><section class="debate-section"><span class="badge">INTERPRETATIE · Aannames</span><h2>Zwakke plekken & onzekerheden</h2>${list(analysis.weakPoints)}</section><section class="debate-section"><span class="badge">DEBATVRAAG · Kritisch bevragen</span><h2>Vragen voor aan tafel</h2>${list(analysis.questions)}</section></article>`);bindFavorites([article]);document.querySelector('#share').addEventListener('click',async()=>{const url=location.href;try{await navigator.clipboard.writeText(url);document.querySelector('#share').textContent='Link gekopieerd';}catch{window.prompt('Kopieer deze link:',url);}});}catch(error){shell('Debatmodus','De analyse is niet beschikbaar.',empty('Debatanalyse kon niet worden geladen.',error.message||'Probeer het later opnieuw.'));}}
function trainer(){let round=0;const render=()=>{shell('Debattrainer','Oefen één argument per ronde.',`<section class="trainer"><label for="statement"><h2>Jouw debatstelling</h2></label><textarea id="statement" rows="3" placeholder="Bijvoorbeeld: Moet Nederland strengere klimaatregels invoeren?"></textarea><label for="argument"><h2>Jouw argument</h2></label><textarea id="argument" rows="5" placeholder="Formuleer één onderbouwd argument."></textarea><p><button class="button" id="coach">Vraag feedback →</button></p><p class="notice">AI-feedback is een oefenhulp, geen feitelijke beoordeling. Controleer claims altijd met betrouwbare bronnen.</p><div id="coach-result" class="trainer-grid"></div></section>`);document.querySelector('#coach').addEventListener('click',async()=>{const button=document.querySelector('#coach'),statement=document.querySelector('#statement').value,argument=document.querySelector('#argument').value;button.disabled=true;button.textContent='Feedback wordt gemaakt…';try{const result=await trainerRound(statement,argument,++round);const f=result.feedback;document.querySelector('#coach-result').innerHTML=[['Feedback',f.feedback],['Argumenttype',f.argumentType],['Mogelijke zwakke plek',f.weakPoint],['Tegenargument',f.counterArgument],['Vervolgvraag',f.followUpQuestion],['Volgende oefening',f.nextExercise]].map(([label,text])=>`<article><span class="badge">${escapeHtml(label)}</span><p>${escapeHtml(text)}</p></article>`).join('');}catch(error){document.querySelector('#coach-result').innerHTML=empty('Trainer tijdelijk niet beschikbaar.',error.message);}finally{button.disabled=false;button.textContent='Vraag feedback →';}});};render();}
function favoritePage(){const items=favorites();shell('Favorieten','Je leeslijst staat uitsluitend in de lokale browseropslag.',items.length?`<div class="grid">${items.map(card).join('')}</div>`:empty('Nog geen favorieten','Bewaar een onderwerp of debat om het hier terug te vinden.'));bindFavorites(items);}
function archive(){shell('Archief','De vijf meest recente artikelen uit de nieuwsservice.',`<div id="archive-results"></div>`);getLatestNews().then(feed=>{document.querySelector('#archive-results').innerHTML=`<div class="grid">${feed.articles.map(card).join('')}</div>`;bindFavorites(feed.articles);}).catch(error=>document.querySelector('#archive-results').innerHTML=empty('Archief tijdelijk niet beschikbaar.',error.message));}
function admin(){shell('Beheer','Dit scherm is bewust niet functioneel zonder server-side sessie en rolcontrole.',`<section class="admin"><h2>Veilige aansluiting vereist</h2><p>Nieuwsbeheer, debatbewerking en een handmatige update horen uitsluitend achter server-side authenticatie en autorisatie. Deze frontend kent geen accounts, rollen, wachtwoorden of secrets.</p><p class="notice">Voeg later beveiligde endpoints toe: <code>GET/PATCH /api/admin/articles</code>, <code>POST /api/admin/news/refresh</code> en audit-log endpoints.</p></section>`);}
function notFound(){shell('Pagina niet gevonden','Controleer de URL of keer terug naar de redactie.',empty('404','Deze route bestaat niet.',`<a class="button" href="/" data-link>Naar de homepage</a>`));}
function route(){const path=decodeURIComponent(location.pathname);menu.classList.remove('open');menuButton.setAttribute('aria-expanded','false');if(path==='/'||path==='/nieuws')newsPage();else if(path.startsWith('/categorie/')){const category=categories.find(item=>item.toLowerCase()===path.slice(11).replaceAll('-',' '));category?newsPage(category):notFound();}else if(path.startsWith('/debat/'))debate(path.slice(7));else if(path==='/debattrainer')trainer();else if(path==='/favorieten')favoritePage();else if(path==='/archief')archive();else if(path==='/admin')admin();else notFound();}
document.addEventListener('click',event=>{const link=event.target.closest('a[data-link]');if(!link)return;event.preventDefault();history.pushState({},'',link.getAttribute('href'));route();});addEventListener('popstate',route);updateFavoriteCount();route();
